import pathlib

rawdata_path = pathlib.Path(r'')
click_path = pathlib.Path(r'')
preprocessed_path = pathlib.Path(r'')
predictor_path = pathlib.Path(r'')
wav_path =  pathlib.Path(r'')
wav_switch_path = pathlib.Path(r'')
oss_path =  pathlib.Path(r'')
oss_switching_path = pathlib.Path(r'')
zil_path = pathlib.Path(r'')
zil_switch_path = pathlib.Path(r'')
ossa_path = pathlib.Path(r'')
ossa_switch_path = pathlib.Path(r'')
gt_path = pathlib.Path(r'')
gt_switch_path = pathlib.Path(r'')
speech_path = pathlib.Path(r'')
randomization_path = pathlib.Path(r'')
pnd_path = pathlib.Path(r'')
post_analysis_path = pathlib.Path(r'')